opt_in_rules: # some rules are only opt-in
  - force_unwrapping
  # - indentation_width
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length: 110
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    warning: 1
    error: 1
nesting:
  type_level: 3
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)

